from .company_specification import CompanySpecification
from .employee_statement_specification import EmployeeStatementSpecification
from .salary_statement_history_specification import SalaryStatementHistorySpecification
from .user_in_out_specification import UserInOutSpecification
