from rest_framework import serializers

class UserSerializer(serializers.Serializer):
    userId = serializers.IntegerField(required=False, allow_null=True)
    firstName = serializers.CharField(required=True)
    lastName = serializers.CharField(required=True)
    middleName = serializers.CharField(required=False, allow_null=True)
    email = serializers.CharField(required=True)
    phone = serializers.CharField(required=True)
    password = serializers.CharField(required=True)
    hourlyRate = serializers.IntegerField(required=False, allow_null=True)
    gender = serializers.CharField(required=False, allow_null=True)
    personalIdentificationNumber = serializers.CharField(required=True)
    address1 = serializers.CharField(required=False, allow_null=True)
    address2 = serializers.CharField(required=False, allow_null=True)
    city = serializers.CharField(required=False, allow_null=True)
    zipCode = serializers.CharField(required=False, allow_null=True)
    country = serializers.CharField(required=False, allow_null=True)
    state = serializers.CharField(required=False, allow_null=True)
    birthDate = serializers.CharField(required=False, allow_null=True)
    emergencyContact = serializers.CharField(required=False, allow_null=True)
    contactPhone = serializers.CharField(required=False, allow_null=True)
    relationship = serializers.CharField(required=False, allow_null=True)
    departmentId = serializers.IntegerField(required=True)
    roleId = serializers.IntegerField(required=True)
    userShiftId = serializers.IntegerField(required=False, allow_null=True)
    contractorId = serializers.IntegerField(required=False, allow_null=True)
    roleName = serializers.CharField(required=False, allow_null=True)
    profileImage = serializers.CharField(required=False, allow_null=True)
    userName = serializers.CharField(required=True)
