from django.db import models

class WeeklyOff(models.Model):
    id = models.AutoField(primary_key=True, db_column='id')
    name = models.CharField(max_length=255)
    description = models.CharField(max_length=255, null=True, blank=True)
    isDefault = models.IntegerField(null=True, blank=True, db_column='is_default')
    sundayAll = models.BooleanField(default=False, null=True, blank=True, db_column='sunday_all')
    sunday1st = models.BooleanField(default=False, null=True, blank=True, db_column='sunday_1st')
    sunday2nd = models.BooleanField(default=False, null=True, blank=True, db_column='sunday_2nd')
    sunday3rd = models.BooleanField(default=False, null=True, blank=True, db_column='sunday_3rd')
    sunday4th = models.BooleanField(default=False, null=True, blank=True, db_column='sunday_4th')
    sunday5th = models.BooleanField(default=False, null=True, blank=True, db_column='sunday_5th')
    mondayAll = models.BooleanField(default=False, null=True, blank=True, db_column='monday_all')
    monday1st = models.BooleanField(default=False, null=True, blank=True, db_column='monday_1st')
    monday2nd = models.BooleanField(default=False, null=True, blank=True, db_column='monday_2nd')
    monday3rd = models.BooleanField(default=False, null=True, blank=True, db_column='monday_3rd')
    monday4th = models.BooleanField(default=False, null=True, blank=True, db_column='monday_4th')
    monday5th = models.BooleanField(default=False, null=True, blank=True, db_column='monday_5th')
    tuesdayAll = models.BooleanField(default=False, null=True, blank=True, db_column='tuesday_all')
    tuesday1st = models.BooleanField(default=False, null=True, blank=True, db_column='tuesday_1st')
    tuesday2nd = models.BooleanField(default=False, null=True, blank=True, db_column='tuesday_2nd')
    tuesday3rd = models.BooleanField(default=False, null=True, blank=True, db_column='tuesday_3rd')
    tuesday4th = models.BooleanField(default=False, null=True, blank=True, db_column='tuesday_4th')
    tuesday5th = models.BooleanField(default=False, null=True, blank=True, db_column='tuesday_5th')
    wednesdayAll = models.BooleanField(default=False, null=True, blank=True, db_column='wednesday_all')
    wednesday1st = models.BooleanField(default=False, null=True, blank=True, db_column='wednesday_1st')
    wednesday2nd = models.BooleanField(default=False, null=True, blank=True, db_column='wednesday_2nd')
    wednesday3rd = models.BooleanField(default=False, null=True, blank=True, db_column='wednesday_3rd')
    wednesday4th = models.BooleanField(default=False, null=True, blank=True, db_column='wednesday_4th')
    wednesday5th = models.BooleanField(default=False, null=True, blank=True, db_column='wednesday_5th')
    thursdayAll = models.BooleanField(default=False, null=True, blank=True, db_column='thursday_all')
    thursday1st = models.BooleanField(default=False, null=True, blank=True, db_column='thursday_1st')
    thursday2nd = models.BooleanField(default=False, null=True, blank=True, db_column='thursday_2nd')
    thursday3rd = models.BooleanField(default=False, null=True, blank=True, db_column='thursday_3rd')
    thursday4th = models.BooleanField(default=False, null=True, blank=True, db_column='thursday_4th')
    thursday5th = models.BooleanField(default=False, null=True, blank=True, db_column='thursday_5th')
    fridayAll = models.BooleanField(default=False, null=True, blank=True, db_column='friday_all')
    friday1st = models.BooleanField(default=False, null=True, blank=True, db_column='friday_1st')
    friday2nd = models.BooleanField(default=False, null=True, blank=True, db_column='friday_2nd')
    friday3rd = models.BooleanField(default=False, null=True, blank=True, db_column='friday_3rd')
    friday4th = models.BooleanField(default=False, null=True, blank=True, db_column='friday_4th')
    friday5th = models.BooleanField(default=False, null=True, blank=True, db_column='friday_5th')
    saturdayAll = models.BooleanField(default=False, null=True, blank=True, db_column='saturday_all')
    saturday1st = models.BooleanField(default=False, null=True, blank=True, db_column='saturday_1st')
    saturday2nd = models.BooleanField(default=False, null=True, blank=True, db_column='saturday_2nd')
    saturday3rd = models.BooleanField(default=False, null=True, blank=True, db_column='saturday_3rd')
    saturday4th = models.BooleanField(default=False, null=True, blank=True, db_column='saturday_4th')
    saturday5th = models.BooleanField(default=False, null=True, blank=True, db_column='saturday_5th')
    companyEmployee = models.ForeignKey('CompanyEmployee', on_delete=models.SET_NULL, db_column='created_by', null=True, blank=True, related_name='+')
    companyDetails = models.ForeignKey('CompanyDetails', on_delete=models.CASCADE, db_column='company_id', null=True, blank=True, related_name='+')

    class Meta:
        db_table = 'weekly_off'
        app_label = 'common'
