from rest_framework import serializers

class SalaryStatementHistorySerializer(serializers.Serializer):
    id = serializers.IntegerField(required=False, allow_null=True)
    clockInOutId = serializers.IntegerField(required=False, allow_null=True)
    companyId = serializers.IntegerField(required=False, allow_null=True)
    employeeId = serializers.IntegerField(required=False, allow_null=True)
    employeeName = serializers.CharField(required=False, allow_null=True)
    departmentId = serializers.IntegerField(required=False, allow_null=True)
    departmentName = serializers.CharField(required=False, allow_null=True)
    basicSalary = serializers.IntegerField(required=False, allow_null=True)
    totalEarnSalary = serializers.IntegerField(required=False, allow_null=True)
    otAmount = serializers.IntegerField(required=False, allow_null=True)
    pfAmount = serializers.IntegerField(required=False, allow_null=True)
    totalPfAmount = serializers.IntegerField(required=False, allow_null=True)
    pfPercentage = serializers.IntegerField(required=False, allow_null=True)
    ptAmount = serializers.IntegerField(required=False, allow_null=True)
    totalEarnings = serializers.IntegerField(required=False, allow_null=True)
    totalPenaltyAmount = serializers.IntegerField(required=False, allow_null=True)
    otherDeductions = serializers.IntegerField(required=False, allow_null=True)
    totalDeductions = serializers.IntegerField(required=False, allow_null=True)
    netSalary = serializers.IntegerField(required=False, allow_null=True)
    year = serializers.IntegerField(required=False, allow_null=True)
    monthNumber = serializers.IntegerField(required=False, allow_null=True)
    monthYear = serializers.CharField(required=False, allow_null=True)
    totalPaidDays = serializers.IntegerField(required=False, allow_null=True)
    totalWorkingDays = serializers.IntegerField(required=False, allow_null=True)
    totalWorkingHours = serializers.FloatField(required=False, allow_null=True)
    totalDays = serializers.IntegerField(required=False, allow_null=True)
    startDate = serializers.CharField(required=False, allow_null=True)
    endDate = serializers.CharField(required=False, allow_null=True)
    timeZone = serializers.CharField(required=False, allow_null=True)
    note = serializers.CharField(required=False, allow_null=True)
    generatedBy = serializers.IntegerField(required=False, allow_null=True)
    deductionsList = serializers.JSONField(required=False, allow_null=True)  # Nested: List<DeductionsDto>
    allowanceList = serializers.JSONField(required=False, allow_null=True)  # Nested: List<DeductionsDto>
    used_leave = serializers.IntegerField(required=False, allow_null=True)

