"""
Django settings for django_project project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

import pymysql

pymysql.install_as_MySQLdb()

# Bypass MySQL/MariaDB version check
from django.db.backends.mysql.base import DatabaseWrapper
from django.db.backends.mysql.features import DatabaseFeatures
DatabaseWrapper.check_database_version_supported = lambda self: None
DatabaseFeatures.can_return_columns_from_insert = property(
    lambda self: self.connection.mysql_is_mariadb and self.connection.mysql_version >= (10, 5, 0)
)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-&@ep7m7+%-$abrv-q=5+uw32evl85dprn&psp!u+8i!xu)q5)o'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'drf_spectacular',
    'common',
    'users_app',
    'companyDetails_app',
    'companyAction_app',
    'companyFunctionality_app',
    'companyModule_app',
    'companyRoleActions_app',
    'companyEmployeeRole_app',
    'companyShift_app',
    'companyTheme_app',
    'contractor_app',
    'country_app',
    'countryToState_app',
    'deductions_app',
    'department_app',
    'employeeBackAccountInfo_app',
    'employeeleavemaster_app',
    'employeeType_app',
    'employmentInfo_app',
    'holidayTemplates_app',
    'holidayTemplateDetails_app',
    'locations_app',
    'leavetype_app',
    'overtimeRules_app',
    'attendancePenaltyRules_app',
    'userShift_app',
    'weeklyOff_app',
    'actions_app',
    'functionality_app',
    'module_app',
    'roles_app',
    'companyReport_app',
    'userInOut_app',
    'salaryStatementHistory_app',
    'salaryStatementMaster_app',
    'companyEmployee_app',
    'employeeStatements_app',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True

from corsheaders.defaults import default_headers
CORS_ALLOW_HEADERS = list(default_headers) + [
    'access-control-allow-headers',
    'access-control-allow-origin',
    'access-control-allow-methods',
]

ROOT_URLCONF = 'calcsalary.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'calcsalary.wsgi.application'


# Environment Selection & Configurations
ENV = "local"
# ENV = "prod"
if ENV == "local":
    DEBUG = True
    from .env_settings.local import *
else:
    DEBUG = True
    from .env_settings.prod import *

# Database & Security Configuration
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': db_name,
        'USER': username,
        'PASSWORD': password,
        'HOST': host,
        'PORT': port,
        'OPTIONS': {
            'charset': 'utf8mb4',
        }
    }
}

# JWT Authentication Config
JWT_SECRET_KEY = jwt_secret_key
JWT_EXPIRATION_HOURS = jwt_expiration_hours

# User Content / Drive Paths
TIMESHEETPRO_DRIVE = timeSheetProDrive
IMAGE_CONTEXT_PATH = imageContextPath


# Email Configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = mail_host
EMAIL_PORT = mail_port
EMAIL_USE_TLS = mail_smtp_starttls_enable
EMAIL_HOST_USER = mail_username
EMAIL_HOST_PASSWORD = mail_password
DEFAULT_FROM_EMAIL = mail_from
EMAIL_FROM_NAME = mail_fromName


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'common.auth.authentication.JWTAuthentication',
    ],
    'EXCEPTION_HANDLER': 'common.exception.exception_handler.custom_exception_handler',
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'Calcsalary API',
    'DESCRIPTION': 'API documentation for Calcsalary system.',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
    'SECURITY': [
        {
            'BearerAuth': [],
        }
    ],
    'APPEND_COMPONENTS': {
        'securitySchemes': {
            'BearerAuth': {
                'type': 'http',
                'scheme': 'bearer',
                'bearerFormat': 'JWT',
                'description': 'Enter JWT token in format: "Bearer <token>"'
            }
        }
    }
}
# Email Settings
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = locals().get('mail_host', 'smtp.gmail.com')
EMAIL_PORT = locals().get('mail_port', 587)
EMAIL_USE_TLS = locals().get('mail_smtp_starttls_enable', True)
EMAIL_HOST_USER = locals().get('mail_username', '')
EMAIL_HOST_PASSWORD = locals().get('mail_password', '')
DEFAULT_FROM_EMAIL = locals().get('mail_from', '')
EMAIL_FROM_NAME = locals().get('mail_fromName', 'TimeSheetsPro-Support')
