from django.db import models

class CompanyEmployee(models.Model):
    employeeId = models.AutoField(primary_key=True, db_column='id')
    companyDetails = models.ForeignKey('CompanyDetails', on_delete=models.SET_NULL, db_column='company_id', null=True, blank=True, related_name='+')
    roles = models.ForeignKey('CompanyEmployeeRoles', on_delete=models.SET_NULL, db_column='role_id', null=True, blank=True, related_name='+')
    userName = models.CharField(max_length=255, null=True, blank=True, db_column='user_name')
    firstName = models.CharField(max_length=255, null=True, blank=True, db_column='first_name')
    lastName = models.CharField(max_length=255, null=True, blank=True, db_column='last_name')
    email = models.CharField(max_length=255, null=True, blank=True)
    password = models.CharField(max_length=255, null=True, blank=True)
    phone = models.CharField(max_length=255, null=True, blank=True)
    emergencyPhone = models.CharField(max_length=255, null=True, blank=True, db_column='emergency_phone')
    altPhone = models.CharField(max_length=255, null=True, blank=True, db_column='alt_phone')
    profileImage = models.CharField(max_length=255, null=True, blank=True, db_column='profile_image')
    city = models.CharField(max_length=255, null=True, blank=True)
    state = models.CharField(max_length=255, null=True, blank=True)
    country = models.CharField(max_length=255, null=True, blank=True)
    hourlyRate = models.FloatField(null=True, blank=True, db_column='hourly_rate')
    address1 = models.CharField(max_length=255, null=True, blank=True)
    address2 = models.CharField(max_length=255, null=True, blank=True)
    gender = models.CharField(max_length=255, null=True, blank=True)
    zipCode = models.CharField(max_length=255, null=True, blank=True, db_column='zip_code')
    dob = models.DateField(null=True, blank=True)
    middleName = models.CharField(max_length=255, null=True, blank=True, db_column='middle_name')
    emergencyContact = models.CharField(max_length=255, null=True, blank=True, db_column='emergency_contact')
    contactPhone = models.CharField(max_length=255, null=True, blank=True, db_column='contact_phone')
    relationship = models.CharField(max_length=255, null=True, blank=True)
    companyShift = models.ForeignKey('CompanyShift', on_delete=models.SET_NULL, db_column='shift_id', null=True, blank=True, related_name='+')
    department = models.ForeignKey('Department', on_delete=models.SET_NULL, db_column='department_id', null=True, blank=True, related_name='+')
    employeeType = models.ForeignKey('EmployeeType', on_delete=models.SET_NULL, db_column='employee_type', null=True, blank=True, related_name='+')
    payPeriod = models.CharField(max_length=255, null=True, blank=True, db_column='pay_period')
    hiredDate = models.DateField(null=True, blank=True, db_column='hired_date')
    isActive = models.IntegerField(null=True, blank=True, db_column='is_active')
    companyLocation = models.CharField(max_length=255, null=True, blank=True, db_column='company_location')
    checkGeofence = models.IntegerField(null=True, blank=True, db_column='check_geofence')
    embedding = models.JSONField(null=True, blank=True)
    bloodGroup = models.CharField(max_length=255, null=True, blank=True, db_column='blood_group')
    aadharImage = models.CharField(max_length=255, null=True, blank=True, db_column='aadhar_image')
    isPf = models.BooleanField(default=False, null=True, blank=True, db_column='is_pf')
    pfType = models.CharField(max_length=255, null=True, blank=True, db_column='pf_type')
    pfPercentage = models.IntegerField(null=True, blank=True, db_column='pf_percentage')
    isPt = models.BooleanField(default=False, null=True, blank=True, db_column='is_pt')
    ptAmount = models.IntegerField(null=True, blank=True, db_column='pt_amount')
    pfAmount = models.IntegerField(null=True, blank=True, db_column='pf_amount')
    basicSalary = models.IntegerField(null=True, blank=True, db_column='basic_salary')
    grossSalary = models.IntegerField(null=True, blank=True, db_column='gross_salary')
    canteenType = models.CharField(max_length=255, null=True, blank=True, db_column='canteen_type')
    canteenAmount = models.IntegerField(null=True, blank=True, db_column='canteen_amount')
    lunchBreak = models.IntegerField(null=True, blank=True, db_column='lunch_break')
    workingHoursIncludeLunch = models.FloatField(null=True, blank=True, db_column='working_hours_include_lunch')
    overtimeRules = models.ForeignKey('OvertimeRules', on_delete=models.SET_NULL, db_column='ot_id', null=True, blank=True, related_name='+')
    weeklyOff = models.ForeignKey('WeeklyOff', on_delete=models.SET_NULL, db_column='weekly_off', null=True, blank=True, related_name='+')
    holidayTemplates = models.ForeignKey('HolidayTemplates', on_delete=models.SET_NULL, db_column='holiday_template', null=True, blank=True, related_name='+')
    lateEntryPenaltyRule = models.BooleanField(default=False, null=True, blank=True, db_column='late_entry_penalty_rule')
    earlyExitPenaltyRule = models.BooleanField(default=False, null=True, blank=True, db_column='early_exit_penalty_rule')

    class Meta:
        db_table = 'company_employees'
        app_label = 'common'
