# Auto-generated model imports
from .actions.actions import Actions
from .attendancepenaltyrules.attendancepenaltyrules import AttendancePenaltyRules
from .companyactions.companyactions import CompanyActions
from .companydetails.companydetails import CompanyDetails
from .companyemployee.companyemployee import CompanyEmployee
from .companyemployeeroles.companyemployeeroles import CompanyEmployeeRoles
from .companyfunctionality.companyfunctionality import CompanyFunctionality
from .companymoduleactions.companymoduleactions import CompanyModuleActions
from .companymodules.companymodules import CompanyModules
from .companyrolemoduleactions.companyrolemoduleactions import CompanyRoleModuleActions
from .companyshift.companyshift import CompanyShift
from .companytheme.companytheme import CompanyTheme
from .contractor.contractor import Contractor
from .country.country import Country
from .countrytostate.countrytostate import CountryToState
from .deductions.deductions import Deductions
from .department.department import Department
from .employeebackaccountinfo.employeebackaccountinfo import EmployeeBackAccountInfo
from .employeeleavemaster.employeeleavemaster import EmployeeLeaveMaster
from .employeetype.employeetype import EmployeeType
from .employmentinfo.employmentinfo import EmploymentInfo
from .functionality.functionality import Functionality
from .holidaytemplatedetails.holidaytemplatedetails import HolidayTemplateDetails
from .holidaytemplates.holidaytemplates import HolidayTemplates
from .leavetype.leavetype import LeaveType
from .locations.locations import Locations
from .module.module import Module
from .moduleactions.moduleactions import ModuleActions
from .overtimerules.overtimerules import OvertimeRules
from .rolemoduleactions.rolemoduleactions import RoleModuleActions
from .roles.roles import Roles
from .salarystatementhistory.salarystatementhistory import SalaryStatementHistory
from .salarystatementmaster.salarystatementmaster import SalaryStatementMaster
from .userinout.userinout import UserInOut
from .users.users import Users
from .usershift.usershift import UserShift
from .weeklyoff.weeklyoff import WeeklyOff
