from rest_framework import serializers

class WeeklyOffSerializer(serializers.Serializer):
    id = serializers.IntegerField(required=False, allow_null=True)
    name = serializers.CharField(required=True)
    description = serializers.CharField(required=False, allow_null=True, allow_blank=True)
    isDefault = serializers.IntegerField(required=False, allow_null=True)
    sundayAll = serializers.BooleanField(default=False)
    sunday1st = serializers.BooleanField(default=False)
    sunday2nd = serializers.BooleanField(default=False)
    sunday3rd = serializers.BooleanField(default=False)
    sunday4th = serializers.BooleanField(default=False)
    sunday5th = serializers.BooleanField(default=False)
    mondayAll = serializers.BooleanField(default=False)
    monday1st = serializers.BooleanField(default=False)
    monday2nd = serializers.BooleanField(default=False)
    monday3rd = serializers.BooleanField(default=False)
    monday4th = serializers.BooleanField(default=False)
    monday5th = serializers.BooleanField(default=False)
    tuesdayAll = serializers.BooleanField(default=False)
    tuesday1st = serializers.BooleanField(default=False)
    tuesday2nd = serializers.BooleanField(default=False)
    tuesday3rd = serializers.BooleanField(default=False)
    tuesday4th = serializers.BooleanField(default=False)
    tuesday5th = serializers.BooleanField(default=False)
    wednesdayAll = serializers.BooleanField(default=False)
    wednesday1st = serializers.BooleanField(default=False)
    wednesday2nd = serializers.BooleanField(default=False)
    wednesday3rd = serializers.BooleanField(default=False)
    wednesday4th = serializers.BooleanField(default=False)
    wednesday5th = serializers.BooleanField(default=False)
    thursdayAll = serializers.BooleanField(default=False)
    thursday1st = serializers.BooleanField(default=False)
    thursday2nd = serializers.BooleanField(default=False)
    thursday3rd = serializers.BooleanField(default=False)
    thursday4th = serializers.BooleanField(default=False)
    thursday5th = serializers.BooleanField(default=False)
    fridayAll = serializers.BooleanField(default=False)
    friday1st = serializers.BooleanField(default=False)
    friday2nd = serializers.BooleanField(default=False)
    friday3rd = serializers.BooleanField(default=False)
    friday4th = serializers.BooleanField(default=False)
    friday5th = serializers.BooleanField(default=False)
    saturdayAll = serializers.BooleanField(default=False)
    saturday1st = serializers.BooleanField(default=False)
    saturday2nd = serializers.BooleanField(default=False)
    saturday3rd = serializers.BooleanField(default=False)
    saturday4th = serializers.BooleanField(default=False)
    saturday5th = serializers.BooleanField(default=False)
    companyId = serializers.IntegerField(required=False, allow_null=True)
    createdBy = serializers.IntegerField(required=False, allow_null=True)
    createdByUsername = serializers.CharField(required=False, allow_null=True)
    assignedEmployeeIds = serializers.JSONField(required=False, allow_null=True)

    def to_internal_value(self, data):
        data_copy = data.copy() if hasattr(data, 'copy') else dict(data)
        for field in ['id', 'isDefault', 'companyId', 'createdBy']:
            if field in data_copy and (data_copy[field] == "" or data_copy[field] == "null" or data_copy[field] is None):
                data_copy[field] = None
        return super().to_internal_value(data_copy)

